spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: jerry
    access-token-validity: 3600000
    refresh-token-validity: 604800000

  security:
    user:
      name: admin      # 기본 사용자 이름
      password: 1234   # 기본 사용자 비밀번호

server:
  port: 8080  # 포트를 8080으로 설정

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      multitap:
        auth: DEBUG