server:
  port: 9100

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3308/auth-service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ThisIsAVeryLongSecretKeyThatIsAtLeast32Characters!
    access-token-validity: 3600000
    refresh-token-validity: 604800000

  security:
    user:
      name: admin
      password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: tnbin98@gmail.com
    password: klus fbql zpuj xoes
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # STARTTLS 활성화

  # Redis 설정
  data:
    redis:
      host: localhost  # Redis 호스트
      port: 6379  # Redis 포트

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    com:
      multitap:
        auth: DEBUG
