spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity: 3600000
    refresh-token-validity: 604800000
  security:
    user:
      name: admin
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: tnbin98@gmail.com
    password: ${SMTP_PASSWORD}  # 민감한 정보는 외부에서 주입
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # STARTTLS 활성화

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      multitap:
        auth: DEBUG

# Redis 설정 추가
data:
  redis:
    host: ${SPRING_REDIS_HOST}  # Redis 호스트
    port: ${SPRING_REDIS_PORT}  # Redis 포트
